CREATE DATABASE BD_PAYSCHOOLEASYSOFT;

CREATE TABLE USUARIO_TBL
(DNI VARCHAR(8) NOT NULL PRIMARY KEY,
 NOMBRE VARCHAR(20),
 APELLIDO  VARCHAR(20),
 USUARIO VARCHAR(50),
 CONTRASEÑA VARCHAR(20),
 TIPO BIT NOT NULL,
 TELEFONO VARCHAR(8),
 DIRECCION  VARCHAR(50));

CREATE TABLE ALUMNO_TBL
(DNI VARCHAR(8) NOT NULL PRIMARY KEY,
 NOMBRE VARCHAR(20),
 FECHANACIMIENTO DATETIME,
 NROMATRICULA INT,
 CODIGOBARRAS INT,
 TUTOR VARCHAR(8),
 FOREIGN KEY (TUTOR) REFERENCES USUARIO_TBL (DNI));

 CREATE TABLE VALORMONETARIO_TBL
(CODIGOVALOR INT NOT NULL PRIMARY KEY,
 VALOR FLOAT);
 
 CREATE TABLE NIVEL_TBL
 (CODIGONIVEL INT NOT NULL PRIMARY KEY,
  DESCRIPCION VARCHAR(10),
  VALORCUOTA FLOAT,
  VALORMATRICULA FLOAT);
 
 CREATE TABLE DESCUENTO_TBL
(CODIGODESCUENTO INT NOT NULL PRIMARY KEY,
 PORCENTAJE INT,
 NIVEL INT,
 FOREIGN KEY (NIVEL) REFERENCES NIVEL_TBL (CODIGONIVEL));
 
 CREATE TABLE CURSO_TBL
(CODIGOCURSO INT NOT NULL PRIMARY KEY,
 AÑO INT,
 CUPO INT,
 NIVEL INT,
 FOREIGN KEY (NIVEL) REFERENCES NIVEL_TBL (CODIGONIVEL));
 
 CREATE TABLE INSCRIPCION_TBL
(NROINSCRIPCION INT NOT NULL PRIMARY KEY,
 FECHAINSCRIPCION DATETIME,
 ABONOMATRICULA BIT,
 ESTAENESPERA BIT,
 CURSO INT,
 FOREIGN KEY (CURSO) REFERENCES CURSO_TBL (CODIGOCURSO),
 DESCUENTO INT,
 FOREIGN KEY (DESCUENTO) REFERENCES DESCUENTO_TBL (CODIGODESCUENTO),
 ALUMNO VARCHAR(8),
 FOREIGN KEY (ALUMNO) REFERENCES ALUMNO_TBL (DNI));
 
CREATE TABLE FACTURA_TBL
(CODIGOFACTURA INT NOT NULL PRIMARY KEY,
 IMPORTE FLOAT,
 FECHAEMISION DATETIME,
 VENCIMIENTO1 DATETIME,
 VENCIMIENTO2 DATETIME,
 INSCRIPCION INT,
 FOREIGN KEY (INSCRIPCION) REFERENCES INSCRIPCION_TBL (NROINSCRIPCION),
 TIPO BIT NOT NULL,
 NROCUOTA INT,
 AÑOCUOTA INT,
 AUMENTO1 INT,
 FOREIGN KEY (AUMENTO1) REFERENCES VALORMONETARIO_TBL (CODIGOVALOR),
 AUMENTO2 INT,
 FOREIGN KEY (AUMENTO2) REFERENCES VALORMONETARIO_TBL (CODIGOVALOR));

CREATE TABLE PAGO_TBL
(CODIGOPAGO INT NOT NULL PRIMARY KEY,
 FECHAPAGO DATETIME,
 FACTURA INT,
 FOREIGN KEY (FACTURA) REFERENCES FACTURA_TBL (CODIGOFACTURA));



